spring:
  application:
    name: browser-scheduler
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${crawler.dataSource.jdbcUrl}
    user: ${crawler.dataSource.username}
    password: ${crawler.dataSource.password}
  security:
    user:
      name: user
server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: '/actuator'
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when-authorized
    env:
      show-values: when-authorized
    configprops:
      show-values: when-authorized
    shutdown:
      enabled: false
crawler:
  dataSource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    jdbcUrl: "jdbc:mysql://${crawler_mysql_host}:${crawler_mysql_port}/${crawler_mysql_db}?useUnicode=yes&characterEncoding=UTF-8&connectTimeout=10000&socketTimeout=10000"
    username: "${crawler_mysql_username}"
    password: "${crawler_mysql_password}"
  hecate:
    endpoints:
      telegramSendPhoto: "http://localhost:8080/telegram/sendPhoto"
browser-scheduler:
  instanceName: Crawler
  gui:
    enable: false
    clearLogInterval: 86400
  browser:
    type: firefox
    maxTask: 1
    pageLoadStrategy: none
    headless: true
  jobParallelism: 1
  springComponentScanBasePackages: "org.kquiet.browserjob"
  jobs:
  - name: BigFunA
    enable: false
    impl: org.kquiet.browserjob.crawler.bigfun.BigFunController
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 600
    scheduleAfterExec: true
    parameters:
      takeScreenshot: "true"
  - name: Sale591A
    enable: true
    impl: org.kquiet.browserjob.crawler.house591.Sale591Controller
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 600
    scheduleAfterExec: true
    parameters:
      takeScreenshot: "true"
  - name: Rent591A
    enable: false
    impl: org.kquiet.browserjob.crawler.house591.Rent591Controller
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 1800
    scheduleAfterExec: true
    parameters:
      takeScreenshot: "true"
  - name: Rent591B
    enable: false
    impl: org.kquiet.browserjob.crawler.house591.Rent591Controller
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 1800
    scheduleAfterExec: true
    parameters:
      takeScreenshot: "true"
  - name: CheckExistPC24Switch
    enable: false
    impl: org.kquiet.browserjob.crawler.obsolete.CheckExistController
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 30
    scheduleAfterExec: true
    parameters:
      botName: "CheckExistPC24Switch"
  - name: CheckExistMoMoSwitch
    enable: false
    impl: org.kquiet.browserjob.crawler.obsolete.CheckExistController
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 30
    scheduleAfterExec: true
    parameters:
      botName: "CheckExistMoMoSwitch"
  - name: Pchome24hBuy
    enable: false
    impl: org.kquiet.browserjob.crawler.obsolete.Pchome24hBuyController
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 1
    scheduleAfterExec: true
    parameters:
      botName: "Pchome24hBuy"
      loginAcc: "${crawler.pchome24h.loginAccount}"
      loginPwd: "${crawler.pchome24h.loginPassword}"
  - name: EasycardJcbRegister
    enable: false
    impl: org.kquiet.browserjob.crawler.obsolete.EasycardJcbRegisterController
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 1
    scheduleAfterExec: true
    parameters:
      autoSubmit: "false"
      parallelism: "5"
      creditcard: "XXXX"
      easycard: "XXXX"
  - name: RailwayBook
    enable: false
    impl: org.kquiet.browserjob.crawler.obsolete.RailwayBookController
    dailyStart: "00:00:00"
    dailyEnd: "00:00:00"
    interval: 1
    scheduleAfterExec: true
    parameters:
      autoSubmit: "false"
      orderCount: "2"
      pid: "XXXX"
      fromStation_1: "1000"
      toStation_1: "7000"
      atDate_1: "2020/06/18"
      trainNo1_1: "412"
      trainNo2_1: "278"
      trainNo3_1: "280"
      quantity_1: "2"
      changeSeat_1: "true"
      fromStation_2: "7000"
      toStation_2: "1000"
      atDate_2: "2020/06/20"
      trainNo1_2: "421"
      trainNo2_2: "225"
      trainNo3_2: "425"
      quantity_2: "2"
      changeSeat_2: "true"
